#ifndef CATALOG_H
#define CATALOG_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#ifndef CATCOMP_NUMBERS
#define CATCOMP_NUMBERS
#endif
#ifndef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif
#endif

#ifdef CATCOMP_BLOCK
#ifndef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_APPDESCRIPTION 100
#define MSG_ABOUT_VERSION 102
#define MSG_ABOUT_OK 105
#define MSG_ABOUT_MUI 106
#define MSG_ABOUT 107
#define MSG_WIN_NEW 300
#define MSG_WIN_NEW_HELP 301
#define MSG_WIN_SWEEP 302
#define MSG_WIN_SWEEP_HELP 303
#define MSG_WIN_UNDO 304
#define MSG_WIN_UNDO_HELP 305
#define MSG_WIN_STATISTICS 306
#define MSG_WIN_STATISTICS_HELP 307
#define MSG_WIN_MOVE 310
#define MSG_WIN_MOVE_HELP 311
#define MSG_TIMER_HELP 312
#define MSG_REQ_NEWGAME 313
#define MSG_REQ_QUIT 314
#define MSG_REQ_GADGETS 315
#define MSG_SCORE_HELP 316
#define MSG_MENU_PROJECT 500
#define MSG_MENU_PROJECT_NEW 501
#define MSG_MENU_PROJECT_SWEEP 502
#define MSG_MENU_PROJECT_UNDO 503
#define MSG_MENU_PROJECT_ABOUT 504
#define MSG_MENU_PROJECT_HELP 505
#define MSG_MENU_PROJECT_STATS 506
#define MSG_MENU_PROJECT_QUIT 507
#define MSG_MENU_SETTINGS 508
#define MSG_MENU_SETTINGS_SOLITON 509
#define MSG_MENU_SETTINGS_MUI 510
#define MSG_MENU_PROFILES 511
#define MSG_MENU_MANPROFILES 512
#define MSG_MENU_GAME 513
#define MSG_MENU_GAME_KLONDIKE 514
#define MSG_MENU_GAME_FREECELL 515
#define MSG_SETTINGS_TITLE 700
#define MSG_SETTINGS_TOPIC 701
#define MSG_SETTINGS_SAVE 702
#define MSG_SETTINGS_SAVE_HELP 703
#define MSG_SETTINGS_USE 704
#define MSG_SETTINGS_USE_HELP 705
#define MSG_SETTINGS_CANCEL 706
#define MSG_SETTINGS_CANCEL_HELP 707
#define MSG_SETTINGS_PATTERN 708
#define MSG_SETTINGS_PATTERN_HELP 709
#define MSG_SETTINGS_CARDSET 710
#define MSG_SETTINGS_CARDSET_HELP 711
#define MSG_SETTINGS_OPEN 712
#define MSG_SETTINGS_OPEN_HELP 713
#define MSG_SETTINGS_BLOCK 714
#define MSG_SETTINGS_BLOCK_HELP 715
#define MSG_SETTINGS_BUTTONS 718
#define MSG_SETTINGS_BUTTONS_HELP 719
#define MSG_SETTINGS_DESIGN 721
#define MSG_SETTINGS_AUTOOPEN 722
#define MSG_SETTINGS_AUTOOPEN_HELP 723
#define MSG_SETTINGS_INDICATOR 724
#define MSG_SETTINGS_INDICATOR_HELP 725
#define MSG_SETTINGS_ANIM 726
#define MSG_SETTINGS_ANIM_HELP 727
#define MSG_SETTINGS_NOANIM 728
#define MSG_SETTINGS_PROFILE 731
#define MSG_SETTINGS_PROFILE_HELP 732
#define MSG_SETTINGS_PROFILES_HELP 733
#define MSG_SETTINGS_NOPROFILE 734
#define MSG_SETTINGS_AUTOTURN 735
#define MSG_SETTINGS_AUTOTURN_HELP 736
#define MSG_SETTINGS_REQS 737
#define MSG_SETTINGS_REQS_HELP 738
#define MSG_SETTINGS_KLONDIKE 739
#define MSG_SETTINGS_FREECELL 740
#define MSG_SETTINGS_STACK 741
#define MSG_SETTINGS_STACK_HELP 742
#define MSG_SETTINGS_EQUALCOLOR 743
#define MSG_SETTINGS_EQUALCOLOR_HELP 744
#define MSG_SETTINGS_REKOBACK 745
#define MSG_SETTINGS_REKOBACK_HELP 746
#define MSG_STATS_TITLE 900
#define MSG_STATS_TOPIC 901
#define MSG_STATS_CLOSE 902
#define MSG_STATS_SCORE 903
#define MSG_STATS_SCORE_HELP 904
#define MSG_STATS_TURNS 905
#define MSG_STATS_TURNS_HELP 906
#define MSG_STATS_WINS 907
#define MSG_STATS_WINS_HELP 908
#define MSG_STATS_LOSSES 909
#define MSG_STATS_LOSSES_HELP 910
#define MSG_WINNER_TITLE 911
#define MSG_WINNER_TEXT 912
#define MSG_STATS_ENTERNAME 913
#define MSG_STATS_CLEARSCORES 914
#define MSG_STATS_CLEARSCORES_HELP 915
#define MSG_STATS_DATE 916
#define MSG_STATS_THISGAME 917
#define MSG_STATS_HIGHSCORES 919
#define MSG_STATS_LNAME 920
#define MSG_STATS_LSCORE 921
#define MSG_STATS_LDATE 922
#define MSG_STATS_TIME 923
#define MSG_STATS_TIME_HELP 924
#define MSG_STATS_SESSIONS 925
#define MSG_STATS_THISSESSION 926
#define MSG_STATS_ALLSESSION 927
#define MSG_STATS_QUOTA 928
#define MSG_STATS_QUOTA_HELP 929
#define MSG_STATS_CLEARREQ 930
#define MSG_PROFILES_TITLE 1100
#define MSG_PROFILES_TOPIC 1101
#define MSG_PROFILES_ADD 1102
#define MSG_PROFILES_ADD_HELP 1103
#define MSG_PROFILES_REM 1104
#define MSG_PROFILES_REM_HELP 1105
#define MSG_PROFILES_CLOSE 1106
#define MSG_ERROR_REQUEST 1200
#define MSG_ERROR_OK 1201
#define MSG_OPENLIB_MUIMASTER 1202
#define MSG_OPENLIB_UTILITY 1203
#define MSG_OPENLIB_INTUITION 1204
#define MSG_OPENLIB_DATATYPES 1205
#define MSG_OPENLIB_LAYERS 1206
#define MSG_OPENLIB_GRAPHICS 1207
#define MSG_CREATE_MAINWINDOW 1208
#define MSG_CREATE_APPLICATION 1209
#define MSG_CREATE_ABOUTCLASS 1210
#define MSG_CREATE_PROFILEMANAGERCLASS 1211
#define MSG_CREATE_CBUTTONCLASS 1212
#define MSG_CREATE_BOARDWINDOWCLASS 1213
#define MSG_CREATE_CSOLITAIRECLASS 1214
#define MSG_CREATE_NONESLIDERCLASS 1215
#define MSG_CREATE_SETTINGSCLASS 1216
#define MSG_CREATE_SOLITONCLASS 1217
#define MSG_CREATE_STATISTICSCLASS 1218
#define MSG_CREATE_CARDGAMECLASS 1219
#define MSG_CARDS_STANDARD_BIG 1220
#define MSG_CARDS_STANDARD_MEDIUM 1221
#define MSG_CARDS_STANDARD_SMALL 1222
#define MSG_LOADING_CARDSET 1223
#define MSG_LOADING_PATTERN 1224
#define MSG_EXTRACTING_CARDSET 1225

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_APPDESCRIPTION_STR "Solitaire card game"
#define MSG_ABOUT_VERSION_STR "Version %s (%s)"
#define MSG_ABOUT_OK_STR "_Ok"
#define MSG_ABOUT_MUI_STR "_About MUI..."
#define MSG_ABOUT_STR "This is an MUI based Amiga card game originally developed by\nKai Nickel in 1997. It is freely available under the GPL license\nsince 2001 and continued by a development team. See the provided\ndocumentation for more information.\n\nA larger set of cardsets can be accessed from the site\nhttp://go.to/rekonet/\nwhich also has lots of links to other information sources.\n\nFor your information the GPL license disclaimer:\n\nThis program is free software; you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation; either version 2 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program; if not, write to the Free Software\nFoundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA"
#define MSG_WIN_NEW_STR "_New"
#define MSG_WIN_NEW_HELP_STR "Start new game"
#define MSG_WIN_SWEEP_STR "_Clean up"
#define MSG_WIN_SWEEP_HELP_STR "Try to move all cards\nto their final position\nauomatically."
#define MSG_WIN_UNDO_STR "_Undo"
#define MSG_WIN_UNDO_HELP_STR "Make last move undone"
#define MSG_WIN_STATISTICS_STR "S_tatistics"
#define MSG_WIN_STATISTICS_HELP_STR "Show game statistics"
#define MSG_WIN_MOVE_STR "_Move"
#define MSG_WIN_MOVE_HELP_STR "This button indicates a\npossible move - and executes\nthat move if you click."
#define MSG_TIMER_HELP_STR "Time elapsed since start of\nthis game. Only running while\nwindow active."
#define MSG_REQ_NEWGAME_STR "Start a new game now?"
#define MSG_REQ_QUIT_STR "Quit Soliton now?"
#define MSG_REQ_GADGETS_STR "* Ok | Cancel"
#define MSG_SCORE_HELP_STR "Game score"
#define MSG_MENU_PROJECT_STR "Game"
#define MSG_MENU_PROJECT_NEW_STR "N\0New game"
#define MSG_MENU_PROJECT_SWEEP_STR "C\0Clean up"
#define MSG_MENU_PROJECT_UNDO_STR "U\0Undo"
#define MSG_MENU_PROJECT_ABOUT_STR "?\0About..."
#define MSG_MENU_PROJECT_HELP_STR "H\0Help..."
#define MSG_MENU_PROJECT_STATS_STR "T\0Statistics..."
#define MSG_MENU_PROJECT_QUIT_STR "Q\0Quit"
#define MSG_MENU_SETTINGS_STR "Settings"
#define MSG_MENU_SETTINGS_SOLITON_STR "S\0Soliton..."
#define MSG_MENU_SETTINGS_MUI_STR "M\0MUI..."
#define MSG_MENU_PROFILES_STR "Profiles"
#define MSG_MENU_MANPROFILES_STR "P\0Manage Profiles..."
#define MSG_MENU_GAME_STR "Gametype"
#define MSG_MENU_GAME_KLONDIKE_STR "K\0Klondike"
#define MSG_MENU_GAME_FREECELL_STR "F\0Freecell"
#define MSG_SETTINGS_TITLE_STR "Soliton <Settings>"
#define MSG_SETTINGS_TOPIC_STR "Settings"
#define MSG_SETTINGS_SAVE_STR "_Save"
#define MSG_SETTINGS_SAVE_HELP_STR "Permanently save settings"
#define MSG_SETTINGS_USE_STR "_Use"
#define MSG_SETTINGS_USE_HELP_STR "Use settings until the next time\nyou start the program"
#define MSG_SETTINGS_CANCEL_STR "_Cancel"
#define MSG_SETTINGS_CANCEL_HELP_STR "Ignore all changes"
#define MSG_SETTINGS_PATTERN_STR "_Pattern"
#define MSG_SETTINGS_PATTERN_HELP_STR "Background pattern of the playfield"
#define MSG_SETTINGS_CARDSET_STR "Ca_rdset"
#define MSG_SETTINGS_CARDSET_HELP_STR "File that contains the cardset"
#define MSG_SETTINGS_OPEN_STR "_Open cards"
#define MSG_SETTINGS_OPEN_HELP_STR "How many cards should be opened\nwhen you click the stack?\nThe higher the harder the game\nwill be."
#define MSG_SETTINGS_BLOCK_STR "B_lock moves"
#define MSG_SETTINGS_BLOCK_HELP_STR "Allow only to move the whole block\nof cards instead of single ones.\nThis will make the game harder."
#define MSG_SETTINGS_BUTTONS_STR "_Buttons"
#define MSG_SETTINGS_BUTTONS_HELP_STR "Do you want to see the buttons?"
#define MSG_SETTINGS_DESIGN_STR "Appearance"
#define MSG_SETTINGS_AUTOOPEN_STR "_Auto open"
#define MSG_SETTINGS_AUTOOPEN_HELP_STR "Automatically turn around the\ntopmost face-down card of a stack.\nThis is just more comfortable\nand does not affect difficulty."
#define MSG_SETTINGS_INDICATOR_STR "_Indicate moves"
#define MSG_SETTINGS_INDICATOR_HELP_STR "Show the 'Move' button every time\nthere is a possible move."
#define MSG_SETTINGS_ANIM_STR "_Fly speed"
#define MSG_SETTINGS_ANIM_HELP_STR "Speed of the cards flying\nto their destination"
#define MSG_SETTINGS_NOANIM_STR "no anim"
#define MSG_SETTINGS_PROFILE_STR "Pro_file"
#define MSG_SETTINGS_PROFILE_HELP_STR "Name of the profile"
#define MSG_SETTINGS_PROFILES_HELP_STR "List of all profiles.\nA profile is a combination\nof a cardset and a pattern\nthat can be referred by a\nsingle name."
#define MSG_SETTINGS_NOPROFILE_STR "<unnamed>"
#define MSG_SETTINGS_AUTOTURN_STR "A_uto open topleft"
#define MSG_SETTINGS_AUTOTURN_HELP_STR "Automatically open the <n>\ncards of the top left stack\nafter turning around that stack.\nThis is just more comfortable\nand does not affect difficulty."
#define MSG_SETTINGS_REQS_STR "Re_quester"
#define MSG_SETTINGS_REQS_HELP_STR "Ask before starting\na new game or quitting\nthe program."
#define MSG_SETTINGS_KLONDIKE_STR "Klondike"
#define MSG_SETTINGS_FREECELL_STR "Freecell"
#define MSG_SETTINGS_STACK_STR "_Stack cards"
#define MSG_SETTINGS_STACK_HELP_STR "How many cards should be already\non the stack when game starts?\nThe higher the harder the game\nwill be."
#define MSG_SETTINGS_EQUALCOLOR_STR "_Equal Color"
#define MSG_SETTINGS_EQUALCOLOR_HELP_STR "Place cards on equal colored cards\ninstead of red/black mixed."
#define MSG_SETTINGS_REKOBACK_STR "REKO _backcards"
#define MSG_SETTINGS_REKOBACK_HELP_STR "Use the 4 stack backcards\nwhen loading a reko cardset."
#define MSG_STATS_TITLE_STR "Soliton <Statistics>"
#define MSG_STATS_TOPIC_STR "Statistics"
#define MSG_STATS_CLOSE_STR "_Ok"
#define MSG_STATS_SCORE_STR "Score"
#define MSG_STATS_SCORE_HELP_STR "Game score"
#define MSG_STATS_TURNS_STR "Turns"
#define MSG_STATS_TURNS_HELP_STR "How many times did you\nturn around the game stack?"
#define MSG_STATS_WINS_STR "Won"
#define MSG_STATS_WINS_HELP_STR "Number of games you\nfinished successfully"
#define MSG_STATS_LOSSES_STR "Lost"
#define MSG_STATS_LOSSES_HELP_STR "Number of games you aborted"
#define MSG_WINNER_TITLE_STR "Congratulations!"
#define MSG_WINNER_TEXT_STR "\nYou finished the game."
#define MSG_STATS_ENTERNAME_STR "Please enter your name:"
#define MSG_STATS_CLEARSCORES_STR "_Clear"
#define MSG_STATS_CLEARSCORES_HELP_STR "Clear all statistics"
#define MSG_STATS_DATE_STR "since %s"
#define MSG_STATS_THISGAME_STR "This game"
#define MSG_STATS_HIGHSCORES_STR "Highscores"
#define MSG_STATS_LNAME_STR "Name"
#define MSG_STATS_LSCORE_STR "Score"
#define MSG_STATS_LDATE_STR "Date"
#define MSG_STATS_TIME_STR "Time"
#define MSG_STATS_TIME_HELP_STR "Game time"
#define MSG_STATS_SESSIONS_STR "Sessions"
#define MSG_STATS_THISSESSION_STR "This\nSession"
#define MSG_STATS_ALLSESSION_STR "All\nSessions"
#define MSG_STATS_QUOTA_STR "Quota"
#define MSG_STATS_QUOTA_HELP_STR "Quota of won games"
#define MSG_STATS_CLEARREQ_STR "Clear all statistics?"
#define MSG_PROFILES_TITLE_STR "Soliton <Manage Profiles>"
#define MSG_PROFILES_TOPIC_STR "Manage Profiles"
#define MSG_PROFILES_ADD_STR "_Add"
#define MSG_PROFILES_ADD_HELP_STR "Create new profile"
#define MSG_PROFILES_REM_STR "_Remove"
#define MSG_PROFILES_REM_HELP_STR "Remove selected profile"
#define MSG_PROFILES_CLOSE_STR "_Ok"
#define MSG_ERROR_REQUEST_STR "Soliton Error"
#define MSG_ERROR_OK_STR "Ok"
#define MSG_OPENLIB_MUIMASTER_STR "Failed to open muimaster.library V17!"
#define MSG_OPENLIB_UTILITY_STR "Failed to open utility.library V38!"
#define MSG_OPENLIB_INTUITION_STR "Failed to open intuition.library V38!"
#define MSG_OPENLIB_DATATYPES_STR "Failed to open datatypes.library V38!"
#define MSG_OPENLIB_LAYERS_STR "Failed to open layers.library V38!"
#define MSG_OPENLIB_GRAPHICS_STR "Failed to open graphics.library V38!"
#define MSG_CREATE_MAINWINDOW_STR "Could not open main window!\nTerminating program."
#define MSG_CREATE_APPLICATION_STR "Failed to create application object!"
#define MSG_CREATE_ABOUTCLASS_STR "Failed to create About class!"
#define MSG_CREATE_PROFILEMANAGERCLASS_STR "Failed to create ProfileManager class!"
#define MSG_CREATE_CBUTTONCLASS_STR "Failed to create CButton class!"
#define MSG_CREATE_BOARDWINDOWCLASS_STR "Failed to create BoardWindow class!"
#define MSG_CREATE_CSOLITAIRECLASS_STR "Could not create CSolitaire class!"
#define MSG_CREATE_NONESLIDERCLASS_STR "Failed to create NoneSlider class!"
#define MSG_CREATE_SETTINGSCLASS_STR "Failed to create Settings class!"
#define MSG_CREATE_SOLITONCLASS_STR "Failed to create Soliton class!"
#define MSG_CREATE_STATISTICSCLASS_STR "Failed to create Statistics class!"
#define MSG_CREATE_CARDGAMECLASS_STR "Failed to create Cardgame class!"
#define MSG_CARDS_STANDARD_BIG_STR "Standard Big"
#define MSG_CARDS_STANDARD_MEDIUM_STR "Standard Medium"
#define MSG_CARDS_STANDARD_SMALL_STR "Standard Small"
#define MSG_LOADING_CARDSET_STR "\033bLoading cardset..."
#define MSG_LOADING_PATTERN_STR "\033bLoading pattern..."
#define MSG_EXTRACTING_CARDSET_STR "\033bExtracting cardset..."

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
    LONG         cca_ID;
    CONST_STRPTR cca_Str;
};

STATIC CONST struct CatCompArrayType CatCompArray[] =
{
    {MSG_APPDESCRIPTION,(CONST_STRPTR)MSG_APPDESCRIPTION_STR},
    {MSG_ABOUT_VERSION,(CONST_STRPTR)MSG_ABOUT_VERSION_STR},
    {MSG_ABOUT_OK,(CONST_STRPTR)MSG_ABOUT_OK_STR},
    {MSG_ABOUT_MUI,(CONST_STRPTR)MSG_ABOUT_MUI_STR},
    {MSG_ABOUT,(CONST_STRPTR)MSG_ABOUT_STR},
    {MSG_WIN_NEW,(CONST_STRPTR)MSG_WIN_NEW_STR},
    {MSG_WIN_NEW_HELP,(CONST_STRPTR)MSG_WIN_NEW_HELP_STR},
    {MSG_WIN_SWEEP,(CONST_STRPTR)MSG_WIN_SWEEP_STR},
    {MSG_WIN_SWEEP_HELP,(CONST_STRPTR)MSG_WIN_SWEEP_HELP_STR},
    {MSG_WIN_UNDO,(CONST_STRPTR)MSG_WIN_UNDO_STR},
    {MSG_WIN_UNDO_HELP,(CONST_STRPTR)MSG_WIN_UNDO_HELP_STR},
    {MSG_WIN_STATISTICS,(CONST_STRPTR)MSG_WIN_STATISTICS_STR},
    {MSG_WIN_STATISTICS_HELP,(CONST_STRPTR)MSG_WIN_STATISTICS_HELP_STR},
    {MSG_WIN_MOVE,(CONST_STRPTR)MSG_WIN_MOVE_STR},
    {MSG_WIN_MOVE_HELP,(CONST_STRPTR)MSG_WIN_MOVE_HELP_STR},
    {MSG_TIMER_HELP,(CONST_STRPTR)MSG_TIMER_HELP_STR},
    {MSG_REQ_NEWGAME,(CONST_STRPTR)MSG_REQ_NEWGAME_STR},
    {MSG_REQ_QUIT,(CONST_STRPTR)MSG_REQ_QUIT_STR},
    {MSG_REQ_GADGETS,(CONST_STRPTR)MSG_REQ_GADGETS_STR},
    {MSG_SCORE_HELP,(CONST_STRPTR)MSG_SCORE_HELP_STR},
    {MSG_MENU_PROJECT,(CONST_STRPTR)MSG_MENU_PROJECT_STR},
    {MSG_MENU_PROJECT_NEW,(CONST_STRPTR)MSG_MENU_PROJECT_NEW_STR},
    {MSG_MENU_PROJECT_SWEEP,(CONST_STRPTR)MSG_MENU_PROJECT_SWEEP_STR},
    {MSG_MENU_PROJECT_UNDO,(CONST_STRPTR)MSG_MENU_PROJECT_UNDO_STR},
    {MSG_MENU_PROJECT_ABOUT,(CONST_STRPTR)MSG_MENU_PROJECT_ABOUT_STR},
    {MSG_MENU_PROJECT_HELP,(CONST_STRPTR)MSG_MENU_PROJECT_HELP_STR},
    {MSG_MENU_PROJECT_STATS,(CONST_STRPTR)MSG_MENU_PROJECT_STATS_STR},
    {MSG_MENU_PROJECT_QUIT,(CONST_STRPTR)MSG_MENU_PROJECT_QUIT_STR},
    {MSG_MENU_SETTINGS,(CONST_STRPTR)MSG_MENU_SETTINGS_STR},
    {MSG_MENU_SETTINGS_SOLITON,(CONST_STRPTR)MSG_MENU_SETTINGS_SOLITON_STR},
    {MSG_MENU_SETTINGS_MUI,(CONST_STRPTR)MSG_MENU_SETTINGS_MUI_STR},
    {MSG_MENU_PROFILES,(CONST_STRPTR)MSG_MENU_PROFILES_STR},
    {MSG_MENU_MANPROFILES,(CONST_STRPTR)MSG_MENU_MANPROFILES_STR},
    {MSG_MENU_GAME,(CONST_STRPTR)MSG_MENU_GAME_STR},
    {MSG_MENU_GAME_KLONDIKE,(CONST_STRPTR)MSG_MENU_GAME_KLONDIKE_STR},
    {MSG_MENU_GAME_FREECELL,(CONST_STRPTR)MSG_MENU_GAME_FREECELL_STR},
    {MSG_SETTINGS_TITLE,(CONST_STRPTR)MSG_SETTINGS_TITLE_STR},
    {MSG_SETTINGS_TOPIC,(CONST_STRPTR)MSG_SETTINGS_TOPIC_STR},
    {MSG_SETTINGS_SAVE,(CONST_STRPTR)MSG_SETTINGS_SAVE_STR},
    {MSG_SETTINGS_SAVE_HELP,(CONST_STRPTR)MSG_SETTINGS_SAVE_HELP_STR},
    {MSG_SETTINGS_USE,(CONST_STRPTR)MSG_SETTINGS_USE_STR},
    {MSG_SETTINGS_USE_HELP,(CONST_STRPTR)MSG_SETTINGS_USE_HELP_STR},
    {MSG_SETTINGS_CANCEL,(CONST_STRPTR)MSG_SETTINGS_CANCEL_STR},
    {MSG_SETTINGS_CANCEL_HELP,(CONST_STRPTR)MSG_SETTINGS_CANCEL_HELP_STR},
    {MSG_SETTINGS_PATTERN,(CONST_STRPTR)MSG_SETTINGS_PATTERN_STR},
    {MSG_SETTINGS_PATTERN_HELP,(CONST_STRPTR)MSG_SETTINGS_PATTERN_HELP_STR},
    {MSG_SETTINGS_CARDSET,(CONST_STRPTR)MSG_SETTINGS_CARDSET_STR},
    {MSG_SETTINGS_CARDSET_HELP,(CONST_STRPTR)MSG_SETTINGS_CARDSET_HELP_STR},
    {MSG_SETTINGS_OPEN,(CONST_STRPTR)MSG_SETTINGS_OPEN_STR},
    {MSG_SETTINGS_OPEN_HELP,(CONST_STRPTR)MSG_SETTINGS_OPEN_HELP_STR},
    {MSG_SETTINGS_BLOCK,(CONST_STRPTR)MSG_SETTINGS_BLOCK_STR},
    {MSG_SETTINGS_BLOCK_HELP,(CONST_STRPTR)MSG_SETTINGS_BLOCK_HELP_STR},
    {MSG_SETTINGS_BUTTONS,(CONST_STRPTR)MSG_SETTINGS_BUTTONS_STR},
    {MSG_SETTINGS_BUTTONS_HELP,(CONST_STRPTR)MSG_SETTINGS_BUTTONS_HELP_STR},
    {MSG_SETTINGS_DESIGN,(CONST_STRPTR)MSG_SETTINGS_DESIGN_STR},
    {MSG_SETTINGS_AUTOOPEN,(CONST_STRPTR)MSG_SETTINGS_AUTOOPEN_STR},
    {MSG_SETTINGS_AUTOOPEN_HELP,(CONST_STRPTR)MSG_SETTINGS_AUTOOPEN_HELP_STR},
    {MSG_SETTINGS_INDICATOR,(CONST_STRPTR)MSG_SETTINGS_INDICATOR_STR},
    {MSG_SETTINGS_INDICATOR_HELP,(CONST_STRPTR)MSG_SETTINGS_INDICATOR_HELP_STR},
    {MSG_SETTINGS_ANIM,(CONST_STRPTR)MSG_SETTINGS_ANIM_STR},
    {MSG_SETTINGS_ANIM_HELP,(CONST_STRPTR)MSG_SETTINGS_ANIM_HELP_STR},
    {MSG_SETTINGS_NOANIM,(CONST_STRPTR)MSG_SETTINGS_NOANIM_STR},
    {MSG_SETTINGS_PROFILE,(CONST_STRPTR)MSG_SETTINGS_PROFILE_STR},
    {MSG_SETTINGS_PROFILE_HELP,(CONST_STRPTR)MSG_SETTINGS_PROFILE_HELP_STR},
    {MSG_SETTINGS_PROFILES_HELP,(CONST_STRPTR)MSG_SETTINGS_PROFILES_HELP_STR},
    {MSG_SETTINGS_NOPROFILE,(CONST_STRPTR)MSG_SETTINGS_NOPROFILE_STR},
    {MSG_SETTINGS_AUTOTURN,(CONST_STRPTR)MSG_SETTINGS_AUTOTURN_STR},
    {MSG_SETTINGS_AUTOTURN_HELP,(CONST_STRPTR)MSG_SETTINGS_AUTOTURN_HELP_STR},
    {MSG_SETTINGS_REQS,(CONST_STRPTR)MSG_SETTINGS_REQS_STR},
    {MSG_SETTINGS_REQS_HELP,(CONST_STRPTR)MSG_SETTINGS_REQS_HELP_STR},
    {MSG_SETTINGS_KLONDIKE,(CONST_STRPTR)MSG_SETTINGS_KLONDIKE_STR},
    {MSG_SETTINGS_FREECELL,(CONST_STRPTR)MSG_SETTINGS_FREECELL_STR},
    {MSG_SETTINGS_STACK,(CONST_STRPTR)MSG_SETTINGS_STACK_STR},
    {MSG_SETTINGS_STACK_HELP,(CONST_STRPTR)MSG_SETTINGS_STACK_HELP_STR},
    {MSG_SETTINGS_EQUALCOLOR,(CONST_STRPTR)MSG_SETTINGS_EQUALCOLOR_STR},
    {MSG_SETTINGS_EQUALCOLOR_HELP,(CONST_STRPTR)MSG_SETTINGS_EQUALCOLOR_HELP_STR},
    {MSG_SETTINGS_REKOBACK,(CONST_STRPTR)MSG_SETTINGS_REKOBACK_STR},
    {MSG_SETTINGS_REKOBACK_HELP,(CONST_STRPTR)MSG_SETTINGS_REKOBACK_HELP_STR},
    {MSG_STATS_TITLE,(CONST_STRPTR)MSG_STATS_TITLE_STR},
    {MSG_STATS_TOPIC,(CONST_STRPTR)MSG_STATS_TOPIC_STR},
    {MSG_STATS_CLOSE,(CONST_STRPTR)MSG_STATS_CLOSE_STR},
    {MSG_STATS_SCORE,(CONST_STRPTR)MSG_STATS_SCORE_STR},
    {MSG_STATS_SCORE_HELP,(CONST_STRPTR)MSG_STATS_SCORE_HELP_STR},
    {MSG_STATS_TURNS,(CONST_STRPTR)MSG_STATS_TURNS_STR},
    {MSG_STATS_TURNS_HELP,(CONST_STRPTR)MSG_STATS_TURNS_HELP_STR},
    {MSG_STATS_WINS,(CONST_STRPTR)MSG_STATS_WINS_STR},
    {MSG_STATS_WINS_HELP,(CONST_STRPTR)MSG_STATS_WINS_HELP_STR},
    {MSG_STATS_LOSSES,(CONST_STRPTR)MSG_STATS_LOSSES_STR},
    {MSG_STATS_LOSSES_HELP,(CONST_STRPTR)MSG_STATS_LOSSES_HELP_STR},
    {MSG_WINNER_TITLE,(CONST_STRPTR)MSG_WINNER_TITLE_STR},
    {MSG_WINNER_TEXT,(CONST_STRPTR)MSG_WINNER_TEXT_STR},
    {MSG_STATS_ENTERNAME,(CONST_STRPTR)MSG_STATS_ENTERNAME_STR},
    {MSG_STATS_CLEARSCORES,(CONST_STRPTR)MSG_STATS_CLEARSCORES_STR},
    {MSG_STATS_CLEARSCORES_HELP,(CONST_STRPTR)MSG_STATS_CLEARSCORES_HELP_STR},
    {MSG_STATS_DATE,(CONST_STRPTR)MSG_STATS_DATE_STR},
    {MSG_STATS_THISGAME,(CONST_STRPTR)MSG_STATS_THISGAME_STR},
    {MSG_STATS_HIGHSCORES,(CONST_STRPTR)MSG_STATS_HIGHSCORES_STR},
    {MSG_STATS_LNAME,(CONST_STRPTR)MSG_STATS_LNAME_STR},
    {MSG_STATS_LSCORE,(CONST_STRPTR)MSG_STATS_LSCORE_STR},
    {MSG_STATS_LDATE,(CONST_STRPTR)MSG_STATS_LDATE_STR},
    {MSG_STATS_TIME,(CONST_STRPTR)MSG_STATS_TIME_STR},
    {MSG_STATS_TIME_HELP,(CONST_STRPTR)MSG_STATS_TIME_HELP_STR},
    {MSG_STATS_SESSIONS,(CONST_STRPTR)MSG_STATS_SESSIONS_STR},
    {MSG_STATS_THISSESSION,(CONST_STRPTR)MSG_STATS_THISSESSION_STR},
    {MSG_STATS_ALLSESSION,(CONST_STRPTR)MSG_STATS_ALLSESSION_STR},
    {MSG_STATS_QUOTA,(CONST_STRPTR)MSG_STATS_QUOTA_STR},
    {MSG_STATS_QUOTA_HELP,(CONST_STRPTR)MSG_STATS_QUOTA_HELP_STR},
    {MSG_STATS_CLEARREQ,(CONST_STRPTR)MSG_STATS_CLEARREQ_STR},
    {MSG_PROFILES_TITLE,(CONST_STRPTR)MSG_PROFILES_TITLE_STR},
    {MSG_PROFILES_TOPIC,(CONST_STRPTR)MSG_PROFILES_TOPIC_STR},
    {MSG_PROFILES_ADD,(CONST_STRPTR)MSG_PROFILES_ADD_STR},
    {MSG_PROFILES_ADD_HELP,(CONST_STRPTR)MSG_PROFILES_ADD_HELP_STR},
    {MSG_PROFILES_REM,(CONST_STRPTR)MSG_PROFILES_REM_STR},
    {MSG_PROFILES_REM_HELP,(CONST_STRPTR)MSG_PROFILES_REM_HELP_STR},
    {MSG_PROFILES_CLOSE,(CONST_STRPTR)MSG_PROFILES_CLOSE_STR},
    {MSG_ERROR_REQUEST,(CONST_STRPTR)MSG_ERROR_REQUEST_STR},
    {MSG_ERROR_OK,(CONST_STRPTR)MSG_ERROR_OK_STR},
    {MSG_OPENLIB_MUIMASTER,(CONST_STRPTR)MSG_OPENLIB_MUIMASTER_STR},
    {MSG_OPENLIB_UTILITY,(CONST_STRPTR)MSG_OPENLIB_UTILITY_STR},
    {MSG_OPENLIB_INTUITION,(CONST_STRPTR)MSG_OPENLIB_INTUITION_STR},
    {MSG_OPENLIB_DATATYPES,(CONST_STRPTR)MSG_OPENLIB_DATATYPES_STR},
    {MSG_OPENLIB_LAYERS,(CONST_STRPTR)MSG_OPENLIB_LAYERS_STR},
    {MSG_OPENLIB_GRAPHICS,(CONST_STRPTR)MSG_OPENLIB_GRAPHICS_STR},
    {MSG_CREATE_MAINWINDOW,(CONST_STRPTR)MSG_CREATE_MAINWINDOW_STR},
    {MSG_CREATE_APPLICATION,(CONST_STRPTR)MSG_CREATE_APPLICATION_STR},
    {MSG_CREATE_ABOUTCLASS,(CONST_STRPTR)MSG_CREATE_ABOUTCLASS_STR},
    {MSG_CREATE_PROFILEMANAGERCLASS,(CONST_STRPTR)MSG_CREATE_PROFILEMANAGERCLASS_STR},
    {MSG_CREATE_CBUTTONCLASS,(CONST_STRPTR)MSG_CREATE_CBUTTONCLASS_STR},
    {MSG_CREATE_BOARDWINDOWCLASS,(CONST_STRPTR)MSG_CREATE_BOARDWINDOWCLASS_STR},
    {MSG_CREATE_CSOLITAIRECLASS,(CONST_STRPTR)MSG_CREATE_CSOLITAIRECLASS_STR},
    {MSG_CREATE_NONESLIDERCLASS,(CONST_STRPTR)MSG_CREATE_NONESLIDERCLASS_STR},
    {MSG_CREATE_SETTINGSCLASS,(CONST_STRPTR)MSG_CREATE_SETTINGSCLASS_STR},
    {MSG_CREATE_SOLITONCLASS,(CONST_STRPTR)MSG_CREATE_SOLITONCLASS_STR},
    {MSG_CREATE_STATISTICSCLASS,(CONST_STRPTR)MSG_CREATE_STATISTICSCLASS_STR},
    {MSG_CREATE_CARDGAMECLASS,(CONST_STRPTR)MSG_CREATE_CARDGAMECLASS_STR},
    {MSG_CARDS_STANDARD_BIG,(CONST_STRPTR)MSG_CARDS_STANDARD_BIG_STR},
    {MSG_CARDS_STANDARD_MEDIUM,(CONST_STRPTR)MSG_CARDS_STANDARD_MEDIUM_STR},
    {MSG_CARDS_STANDARD_SMALL,(CONST_STRPTR)MSG_CARDS_STANDARD_SMALL_STR},
    {MSG_LOADING_CARDSET,(CONST_STRPTR)MSG_LOADING_CARDSET_STR},
    {MSG_LOADING_PATTERN,(CONST_STRPTR)MSG_LOADING_PATTERN_STR},
    {MSG_EXTRACTING_CARDSET,(CONST_STRPTR)MSG_EXTRACTING_CARDSET_STR},
};

#endif /* CATCOMP_ARRAY */


/****************************************************************************/


#ifdef CATCOMP_BLOCK

STATIC CONST UBYTE CatCompBlock[] =
{
    "\x00\x00\x00\x64\x00\x14"
    MSG_APPDESCRIPTION_STR "\x00"
    "\x00\x00\x00\x66\x00\x10"
    MSG_ABOUT_VERSION_STR "\x00"
    "\x00\x00\x00\x69\x00\x04"
    MSG_ABOUT_OK_STR "\x00"
    "\x00\x00\x00\x6A\x00\x0E"
    MSG_ABOUT_MUI_STR "\x00"
    "\x00\x00\x00\x6B\x04\x44"
    MSG_ABOUT_STR "\x00\x00"
    "\x00\x00\x01\x2C\x00\x06"
    MSG_WIN_NEW_STR "\x00\x00"
    "\x00\x00\x01\x2D\x00\x10"
    MSG_WIN_NEW_HELP_STR "\x00\x00"
    "\x00\x00\x01\x2E\x00\x0A"
    MSG_WIN_SWEEP_STR "\x00"
    "\x00\x00\x01\x2F\x00\x3C"
    MSG_WIN_SWEEP_HELP_STR "\x00"
    "\x00\x00\x01\x30\x00\x06"
    MSG_WIN_UNDO_STR "\x00"
    "\x00\x00\x01\x31\x00\x16"
    MSG_WIN_UNDO_HELP_STR "\x00"
    "\x00\x00\x01\x32\x00\x0C"
    MSG_WIN_STATISTICS_STR "\x00"
    "\x00\x00\x01\x33\x00\x16"
    MSG_WIN_STATISTICS_HELP_STR "\x00\x00"
    "\x00\x00\x01\x36\x00\x06"
    MSG_WIN_MOVE_STR "\x00"
    "\x00\x00\x01\x37\x00\x4E"
    MSG_WIN_MOVE_HELP_STR "\x00\x00"
    "\x00\x00\x01\x38\x00\x4A"
    MSG_TIMER_HELP_STR "\x00\x00"
    "\x00\x00\x01\x39\x00\x16"
    MSG_REQ_NEWGAME_STR "\x00"
    "\x00\x00\x01\x3A\x00\x12"
    MSG_REQ_QUIT_STR "\x00"
    "\x00\x00\x01\x3B\x00\x0E"
    MSG_REQ_GADGETS_STR "\x00"
    "\x00\x00\x01\x3C\x00\x0C"
    MSG_SCORE_HELP_STR "\x00\x00"
    "\x00\x00\x01\xF4\x00\x06"
    MSG_MENU_PROJECT_STR "\x00\x00"
    "\x00\x00\x01\xF5\x00\x0C"
    MSG_MENU_PROJECT_NEW_STR "\x00\x00"
    "\x00\x00\x01\xF6\x00\x0C"
    MSG_MENU_PROJECT_SWEEP_STR "\x00\x00"
    "\x00\x00\x01\xF7\x00\x08"
    MSG_MENU_PROJECT_UNDO_STR "\x00\x00"
    "\x00\x00\x01\xF8\x00\x0C"
    MSG_MENU_PROJECT_ABOUT_STR "\x00\x00"
    "\x00\x00\x01\xF9\x00\x0A"
    MSG_MENU_PROJECT_HELP_STR "\x00"
    "\x00\x00\x01\xFA\x00\x10"
    MSG_MENU_PROJECT_STATS_STR "\x00"
    "\x00\x00\x01\xFB\x00\x08"
    MSG_MENU_PROJECT_QUIT_STR "\x00\x00"
    "\x00\x00\x01\xFC\x00\x0A"
    MSG_MENU_SETTINGS_STR "\x00\x00"
    "\x00\x00\x01\xFD\x00\x0E"
    MSG_MENU_SETTINGS_SOLITON_STR "\x00\x00"
    "\x00\x00\x01\xFE\x00\x0A"
    MSG_MENU_SETTINGS_MUI_STR "\x00\x00"
    "\x00\x00\x01\xFF\x00\x0A"
    MSG_MENU_PROFILES_STR "\x00\x00"
    "\x00\x00\x02\x00\x00\x16"
    MSG_MENU_MANPROFILES_STR "\x00\x00"
    "\x00\x00\x02\x01\x00\x0A"
    MSG_MENU_GAME_STR "\x00\x00"
    "\x00\x00\x02\x02\x00\x0C"
    MSG_MENU_GAME_KLONDIKE_STR "\x00\x00"
    "\x00\x00\x02\x03\x00\x0C"
    MSG_MENU_GAME_FREECELL_STR "\x00\x00"
    "\x00\x00\x02\xBC\x00\x14"
    MSG_SETTINGS_TITLE_STR "\x00\x00"
    "\x00\x00\x02\xBD\x00\x0A"
    MSG_SETTINGS_TOPIC_STR "\x00\x00"
    "\x00\x00\x02\xBE\x00\x06"
    MSG_SETTINGS_SAVE_STR "\x00"
    "\x00\x00\x02\xBF\x00\x1A"
    MSG_SETTINGS_SAVE_HELP_STR "\x00"
    "\x00\x00\x02\xC0\x00\x06"
    MSG_SETTINGS_USE_STR "\x00\x00"
    "\x00\x00\x02\xC1\x00\x38"
    MSG_SETTINGS_USE_HELP_STR "\x00\x00"
    "\x00\x00\x02\xC2\x00\x08"
    MSG_SETTINGS_CANCEL_STR "\x00"
    "\x00\x00\x02\xC3\x00\x14"
    MSG_SETTINGS_CANCEL_HELP_STR "\x00\x00"
    "\x00\x00\x02\xC4\x00\x0A"
    MSG_SETTINGS_PATTERN_STR "\x00\x00"
    "\x00\x00\x02\xC5\x00\x24"
    MSG_SETTINGS_PATTERN_HELP_STR "\x00"
    "\x00\x00\x02\xC6\x00\x0A"
    MSG_SETTINGS_CARDSET_STR "\x00\x00"
    "\x00\x00\x02\xC7\x00\x20"
    MSG_SETTINGS_CARDSET_HELP_STR "\x00\x00"
    "\x00\x00\x02\xC8\x00\x0C"
    MSG_SETTINGS_OPEN_STR "\x00"
    "\x00\x00\x02\xC9\x00\x62"
    MSG_SETTINGS_OPEN_HELP_STR "\x00"
    "\x00\x00\x02\xCA\x00\x0E"
    MSG_SETTINGS_BLOCK_STR "\x00\x00"
    "\x00\x00\x02\xCB\x00\x64"
    MSG_SETTINGS_BLOCK_HELP_STR "\x00"
    "\x00\x00\x02\xCE\x00\x0A"
    MSG_SETTINGS_BUTTONS_STR "\x00\x00"
    "\x00\x00\x02\xCF\x00\x20"
    MSG_SETTINGS_BUTTONS_HELP_STR "\x00"
    "\x00\x00\x02\xD1\x00\x0C"
    MSG_SETTINGS_DESIGN_STR "\x00\x00"
    "\x00\x00\x02\xD2\x00\x0C"
    MSG_SETTINGS_AUTOOPEN_STR "\x00\x00"
    "\x00\x00\x02\xD3\x00\x80"
    MSG_SETTINGS_AUTOOPEN_HELP_STR "\x00\x00"
    "\x00\x00\x02\xD4\x00\x10"
    MSG_SETTINGS_INDICATOR_STR "\x00"
    "\x00\x00\x02\xD5\x00\x3C"
    MSG_SETTINGS_INDICATOR_HELP_STR "\x00"
    "\x00\x00\x02\xD6\x00\x0C"
    MSG_SETTINGS_ANIM_STR "\x00\x00"
    "\x00\x00\x02\xD7\x00\x30"
    MSG_SETTINGS_ANIM_HELP_STR "\x00\x00"
    "\x00\x00\x02\xD8\x00\x08"
    MSG_SETTINGS_NOANIM_STR "\x00"
    "\x00\x00\x02\xDB\x00\x0A"
    MSG_SETTINGS_PROFILE_STR "\x00\x00"
    "\x00\x00\x02\xDC\x00\x14"
    MSG_SETTINGS_PROFILE_HELP_STR "\x00"
    "\x00\x00\x02\xDD\x00\x74"
    MSG_SETTINGS_PROFILES_HELP_STR "\x00\x00"
    "\x00\x00\x02\xDE\x00\x0A"
    MSG_SETTINGS_NOPROFILE_STR "\x00"
    "\x00\x00\x02\xDF\x00\x14"
    MSG_SETTINGS_AUTOTURN_STR "\x00\x00"
    "\x00\x00\x02\xE0\x00\x96"
    MSG_SETTINGS_AUTOTURN_HELP_STR "\x00"
    "\x00\x00\x02\xE1\x00\x0C"
    MSG_SETTINGS_REQS_STR "\x00\x00"
    "\x00\x00\x02\xE2\x00\x38"
    MSG_SETTINGS_REQS_HELP_STR "\x00"
    "\x00\x00\x02\xE3\x00\x0A"
    MSG_SETTINGS_KLONDIKE_STR "\x00\x00"
    "\x00\x00\x02\xE4\x00\x0A"
    MSG_SETTINGS_FREECELL_STR "\x00\x00"
    "\x00\x00\x02\xE5\x00\x0E"
    MSG_SETTINGS_STACK_STR "\x00\x00"
    "\x00\x00\x02\xE6\x00\x68"
    MSG_SETTINGS_STACK_HELP_STR "\x00"
    "\x00\x00\x02\xE7\x00\x0E"
    MSG_SETTINGS_EQUALCOLOR_STR "\x00\x00"
    "\x00\x00\x02\xE8\x00\x40"
    MSG_SETTINGS_EQUALCOLOR_HELP_STR "\x00\x00"
    "\x00\x00\x02\xE9\x00\x10"
    MSG_SETTINGS_REKOBACK_STR "\x00"
    "\x00\x00\x02\xEA\x00\x38"
    MSG_SETTINGS_REKOBACK_HELP_STR "\x00\x00"
    "\x00\x00\x03\x84\x00\x16"
    MSG_STATS_TITLE_STR "\x00\x00"
    "\x00\x00\x03\x85\x00\x0C"
    MSG_STATS_TOPIC_STR "\x00\x00"
    "\x00\x00\x03\x86\x00\x04"
    MSG_STATS_CLOSE_STR "\x00"
    "\x00\x00\x03\x87\x00\x06"
    MSG_STATS_SCORE_STR "\x00"
    "\x00\x00\x03\x88\x00\x0C"
    MSG_STATS_SCORE_HELP_STR "\x00\x00"
    "\x00\x00\x03\x89\x00\x06"
    MSG_STATS_TURNS_STR "\x00"
    "\x00\x00\x03\x8A\x00\x34"
    MSG_STATS_TURNS_HELP_STR "\x00\x00"
    "\x00\x00\x03\x8B\x00\x04"
    MSG_STATS_WINS_STR "\x00"
    "\x00\x00\x03\x8C\x00\x2A"
    MSG_STATS_WINS_HELP_STR "\x00"
    "\x00\x00\x03\x8D\x00\x06"
    MSG_STATS_LOSSES_STR "\x00\x00"
    "\x00\x00\x03\x8E\x00\x1C"
    MSG_STATS_LOSSES_HELP_STR "\x00"
    "\x00\x00\x03\x8F\x00\x12"
    MSG_WINNER_TITLE_STR "\x00\x00"
    "\x00\x00\x03\x90\x00\x18"
    MSG_WINNER_TEXT_STR "\x00"
    "\x00\x00\x03\x91\x00\x18"
    MSG_STATS_ENTERNAME_STR "\x00"
    "\x00\x00\x03\x92\x00\x08"
    MSG_STATS_CLEARSCORES_STR "\x00\x00"
    "\x00\x00\x03\x93\x00\x16"
    MSG_STATS_CLEARSCORES_HELP_STR "\x00\x00"
    "\x00\x00\x03\x94\x00\x0A"
    MSG_STATS_DATE_STR "\x00\x00"
    "\x00\x00\x03\x95\x00\x0A"
    MSG_STATS_THISGAME_STR "\x00"
    "\x00\x00\x03\x97\x00\x0C"
    MSG_STATS_HIGHSCORES_STR "\x00\x00"
    "\x00\x00\x03\x98\x00\x06"
    MSG_STATS_LNAME_STR "\x00\x00"
    "\x00\x00\x03\x99\x00\x06"
    MSG_STATS_LSCORE_STR "\x00"
    "\x00\x00\x03\x9A\x00\x06"
    MSG_STATS_LDATE_STR "\x00\x00"
    "\x00\x00\x03\x9B\x00\x06"
    MSG_STATS_TIME_STR "\x00\x00"
    "\x00\x00\x03\x9C\x00\x0A"
    MSG_STATS_TIME_HELP_STR "\x00"
    "\x00\x00\x03\x9D\x00\x0A"
    MSG_STATS_SESSIONS_STR "\x00\x00"
    "\x00\x00\x03\x9E\x00\x0E"
    MSG_STATS_THISSESSION_STR "\x00\x00"
    "\x00\x00\x03\x9F\x00\x0E"
    MSG_STATS_ALLSESSION_STR "\x00\x00"
    "\x00\x00\x03\xA0\x00\x06"
    MSG_STATS_QUOTA_STR "\x00"
    "\x00\x00\x03\xA1\x00\x14"
    MSG_STATS_QUOTA_HELP_STR "\x00\x00"
    "\x00\x00\x03\xA2\x00\x16"
    MSG_STATS_CLEARREQ_STR "\x00"
    "\x00\x00\x04\x4C\x00\x1A"
    MSG_PROFILES_TITLE_STR "\x00"
    "\x00\x00\x04\x4D\x00\x10"
    MSG_PROFILES_TOPIC_STR "\x00"
    "\x00\x00\x04\x4E\x00\x06"
    MSG_PROFILES_ADD_STR "\x00\x00"
    "\x00\x00\x04\x4F\x00\x14"
    MSG_PROFILES_ADD_HELP_STR "\x00\x00"
    "\x00\x00\x04\x50\x00\x08"
    MSG_PROFILES_REM_STR "\x00"
    "\x00\x00\x04\x51\x00\x18"
    MSG_PROFILES_REM_HELP_STR "\x00"
    "\x00\x00\x04\x52\x00\x04"
    MSG_PROFILES_CLOSE_STR "\x00"
    "\x00\x00\x04\xB0\x00\x0E"
    MSG_ERROR_REQUEST_STR "\x00"
    "\x00\x00\x04\xB1\x00\x04"
    MSG_ERROR_OK_STR "\x00\x00"
    "\x00\x00\x04\xB2\x00\x26"
    MSG_OPENLIB_MUIMASTER_STR "\x00"
    "\x00\x00\x04\xB3\x00\x24"
    MSG_OPENLIB_UTILITY_STR "\x00"
    "\x00\x00\x04\xB4\x00\x26"
    MSG_OPENLIB_INTUITION_STR "\x00"
    "\x00\x00\x04\xB5\x00\x26"
    MSG_OPENLIB_DATATYPES_STR "\x00"
    "\x00\x00\x04\xB6\x00\x24"
    MSG_OPENLIB_LAYERS_STR "\x00\x00"
    "\x00\x00\x04\xB7\x00\x26"
    MSG_OPENLIB_GRAPHICS_STR "\x00\x00"
    "\x00\x00\x04\xB8\x00\x32"
    MSG_CREATE_MAINWINDOW_STR "\x00\x00"
    "\x00\x00\x04\xB9\x00\x26"
    MSG_CREATE_APPLICATION_STR "\x00\x00"
    "\x00\x00\x04\xBA\x00\x1E"
    MSG_CREATE_ABOUTCLASS_STR "\x00"
    "\x00\x00\x04\xBB\x00\x28"
    MSG_CREATE_PROFILEMANAGERCLASS_STR "\x00\x00"
    "\x00\x00\x04\xBC\x00\x20"
    MSG_CREATE_CBUTTONCLASS_STR "\x00"
    "\x00\x00\x04\xBD\x00\x24"
    MSG_CREATE_BOARDWINDOWCLASS_STR "\x00"
    "\x00\x00\x04\xBE\x00\x24"
    MSG_CREATE_CSOLITAIRECLASS_STR "\x00\x00"
    "\x00\x00\x04\xBF\x00\x24"
    MSG_CREATE_NONESLIDERCLASS_STR "\x00\x00"
    "\x00\x00\x04\xC0\x00\x22"
    MSG_CREATE_SETTINGSCLASS_STR "\x00\x00"
    "\x00\x00\x04\xC1\x00\x20"
    MSG_CREATE_SOLITONCLASS_STR "\x00"
    "\x00\x00\x04\xC2\x00\x24"
    MSG_CREATE_STATISTICSCLASS_STR "\x00\x00"
    "\x00\x00\x04\xC3\x00\x22"
    MSG_CREATE_CARDGAMECLASS_STR "\x00\x00"
    "\x00\x00\x04\xC4\x00\x0E"
    MSG_CARDS_STANDARD_BIG_STR "\x00\x00"
    "\x00\x00\x04\xC5\x00\x10"
    MSG_CARDS_STANDARD_MEDIUM_STR "\x00"
    "\x00\x00\x04\xC6\x00\x10"
    MSG_CARDS_STANDARD_SMALL_STR "\x00\x00"
    "\x00\x00\x04\xC7\x00\x16"
    MSG_LOADING_CARDSET_STR "\x00\x00"
    "\x00\x00\x04\xC8\x00\x16"
    MSG_LOADING_PATTERN_STR "\x00\x00"
    "\x00\x00\x04\xC9\x00\x18"
    MSG_EXTRACTING_CARDSET_STR "\x00"
};

#endif /* CATCOMP_BLOCK */


/****************************************************************************/


#ifdef CATCOMP_CODE

#ifndef PROTO_LOCALE_H
#define __NOLIBBASE__
#define __NOGLOBALIFACE__
#include <proto/locale.h>
#endif

struct LocaleInfo
{
#ifndef __amigaos4__
    struct Library     *li_LocaleBase;
#else
    struct LocaleIFace *li_ILocale;
#endif
    struct Catalog     *li_Catalog;
};


CONST_STRPTR GetString(struct LocaleInfo *li, LONG stringNum);

CONST_STRPTR GetString(struct LocaleInfo *li, LONG stringNum)
{
#ifndef __amigaos4__
    struct Library     *LocaleBase = li->li_LocaleBase;
#else
    struct LocaleIFace *ILocale    = li->li_ILocale;
#endif
    LONG         *l;
    UWORD        *w;
    CONST_STRPTR  builtIn;

    l = (LONG *)CatCompBlock;

    while (*l != stringNum)
    {
        w = (UWORD *)((ULONG)l + 4);
        l = (LONG *)((ULONG)l + (ULONG)*w + 6);
    }
    builtIn = (CONST_STRPTR)((ULONG)l + 6);

#ifndef __amigaos4__
    if (LocaleBase)
    {
        return GetCatalogStr(li->li_Catalog, stringNum, builtIn);
    }
#else
    if (ILocale)
    {
#ifdef __USE_INLINE__
        return GetCatalogStr(li->li_Catalog, stringNum, builtIn);
#else
        return ILocale->GetCatalogStr(li->li_Catalog, stringNum, builtIn);
#endif
    }
#endif
    return builtIn;
}


#endif /* CATCOMP_CODE */


/****************************************************************************/


#endif /* CATALOG_H */
